### ISSUE TITLE
Spin up time is very high. Can we optimize it?

### ISSUE THREAD

**Issue by ferreiro** [NikolajDL/gcloud-sdk-nodejs#2]
Hey Nikola!

I'm using your image in CircleCI. I noticed the spin up time on subsequent requests is very high (1 minute). Saw their docks, and it seems there may be some options to optimize and cache the image, but I think maybe that's something u have to setup?

![Screen Shot 2022-10-01 at 11 15 46 PM](https://user-images.githubusercontent.com/7242959/193428588-1d989f93-f59c-42bc-846a-0a4f85bd65e4.png)

I don't have any idea with docker, so if you can help that would be epic! https://circleci.com/docs/docker-layer-caching

Pst: Thanks tons for building this, seriously, I was blocked and you unlocked me. It's fun cause don't know Docker and your solution was so clean.

**Comment by NikolajDL** [comment]
Sorry for the late reply, completely missed your message. 

The images tagged as `latest` can be quite large, which will affect spin up time. Have you tried the `alpine-node-16` tag? If you've tried that, is it still slow?

And thank you for the praise. I originally created the Docker image because I needed to work around some limitations in Bitbucket Pipelines, and thought I might as well share it. :-) Glad someone else finds it useful.

**Comment by ferreiro** [comment]
thanks, tried alpine and worked! closing it.

**Comment by NikolajDL** [comment]
Hi Ferreiro,

Just a heads up. I've restructured the Docker hub repo a bit and removed the alpine tags. This is because I've changed the way the image is generated.

The end result is still the same, and the images are even smaller than the former alpine equivalents. 

This may break your build, unless your CI tool has cached the image, but changing the image to `nikolajdl/gcloud-sdk-nodejs:lts` should fix it right away.
